[scene]
name = "Cornell Box"

[scene.environment]
equirect = "../hdri/puresky_4k.hdr"
intensity = 1.0
skybox_exposure = 0.9
path_trace_exposure = 0.25
tonemap_exposure = 1.0
cubemap_size = 512

[[entities]]
id = 1
name = "Main Camera"

[entities.transform]
translation = [0.0, 1.0, -3.25]
rotation = [0.0, 1.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]

[entities.camera]
primary = true
vertical_fov_degrees = 60.0
near = 0.05
far = 100.0

[entities.fly_camera]
move_speed = 1.0
fast_move_multiplier = 4.0
mouse_sensitivity = 0.0015
yaw = 3.14159265
pitch = 0.0
capture_mouse = true



[[entities]]
id = 2
name = "Cornell Box"
model = "CornellBox-Original.gltf"

[entities.transform]
translation = [2.35, -0.75, 0.35]
rotation = [0.0, 90.0, 0.0, 1.0]
scale = [1.0, 1.0, 1.0]


[[entities]]
id = 3
name = "Key Light"

[entities.transform]
rotation = [-0.6, 0.4, 0.0, 1.0]

[entities.light]
type = "directional"
color = [1.0, 0.95, 0.85]
intensity = 3.0
