[scene]
name = "ImageContinuum Demo Scene"

[scene.environment]
equirect = "../hdri/puresky_4k.hdr"
intensity = 1.0
skybox_exposure = 0.9
path_trace_exposure = 0.25
tonemap_exposure = 1.0
cubemap_size = 512

[[entities]]
id = 1
name = "Main Camera"

[entities.transform]
translation = [0.0, 1.5, 5.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [1.0, 1.0, 1.0]

[entities.camera]
primary = true
vertical_fov_degrees = 90.0
near = 0.1
far = 1000.0

[entities.fly_camera]
move_speed = 1.0
fast_move_multiplier = 4.0
mouse_sensitivity = 0.0010
yaw = 0.0
pitch = 0.0
capture_mouse = true


[[entities]]
id = 2
name = "FPS MAP"
model = "FPS_MAP/scene.glb"

[entities.transform]
translation = [0.0, -0.5, -0.85]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [0.222, 0.222, 0.222]

[[entities]]
id = 3
name = "Damaged PBR Helmet"
model = "DamagedHelmet/glTF/DamagedHelmet.gltf"

[entities.transform]
translation = [0.0, -0.15, -1.55]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [0.35, 0.35, 0.35]

[[entities]]
id = 4
name = "Sofa"
model = "GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb"

[entities.transform]
translation = [0.0, -0.51, 1.5]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [0.35, 0.35, 0.35]

[[entities]]
id = 5
name = "Water Bottle"
model = "WaterBottle/glTF-Binary/WaterBottle.glb"

[entities.transform]
translation = [0.0, -0.4, 2.5]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [0.75, 0.75, 0.75]

[[entities]]
id = 6
name = "Sun"

[entities.transform]
rotation = [-0.4, 0.2, 0.0, 1.0]

[entities.light]
type = "directional"
color = [1.0, 0.95, 0.85]
intensity = 4.0



[[entities]]
id = 7
name = "Floor Probe Light Warm"
model = "light_marker_warm.gltf"

[entities.transform]
translation = [-1.15, 0.85, -1.65]
scale = [0.12, 0.12, 0.12]

[entities.light]
type = "point"
color = [1.0, 0.58, 0.32]
intensity = 14.0
range = 3.0

[[entities]]
id = 8
name = "Floor Probe Light Cool"
model = "light_marker_cool.gltf"

[entities.transform]
translation = [1.05, 1.05, -1.25]
scale = [0.12, 0.12, 0.12]

[entities.light]
type = "point"
color = [0.35, 0.62, 1.0]
intensity = 12.0
range = 2.8

[[entities]]
id = 9
name = "Floor Probe Light Green"
model = "light_marker_green.gltf"

[entities.transform]
translation = [-0.35, 1.25, 0.15]
scale = [0.12, 0.12, 0.12]

[entities.light]
type = "point"
color = [0.55, 1.0, 0.62]
intensity = 8.0
range = 2.2

[[entities]]
id = 10
name = "Floor Probe Light Magenta"
model = "light_marker_magenta.gltf"

[entities.transform]
translation = [0.85, 0.95, 0.55]
scale = [0.12, 0.12, 0.12]

[entities.light]
type = "point"
color = [1.0, 0.34, 0.78]
intensity = 9.0
range = 5.4
