[scene]
name = "Skybox Test Scene"

[scene.environment]
equirect = "../hdri/puresky_4k.hdr"
intensity = 1.0

[[entities]]
id = 1
name = "Main Camera"

[entities.transform]
translation = [0.0, 1.5, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [1.0, 1.0, 1.0]

[entities.camera]
primary = true
vertical_fov_degrees = 90.0
near = 0.1
far = 1000.0

[entities.fly_camera]
move_speed = 8.0
fast_move_multiplier = 4.0
mouse_sensitivity = 0.0025
yaw = 0.0
pitch = 0.0
capture_mouse = true

[[entities]]
id = 2
name = "Small Cornell Reference"
model = "CornellBox-Original.gltf"

[entities.transform]
translation = [0.0, -1.0, -6.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale = [0.25, 0.25, 0.25]
