[[assets]]
name = "Cornell full model"
type = "model"
path = "CornellBox-Original.gltf"
load_materials = true
load_textures = true

[[assets]]
name = "Cornell mesh only"
type = "model"
path = "CornellBox-Original.gltf"
load_materials = false
load_textures = false

[[assets]]
name = "Cornell materials/no textures"
type = "model"
path = "CornellBox-Original.gltf"
load_materials = true
load_textures = false

[[assets]]
name = "Cornell raw bytes"
type = "binary"
path = "CornellBox-Original.gltf"

[[assets]]
name = "Cornell text bytes"
type = "binary"
path = "CornellBox-Original.gltf"
null_terminate = true
