[pipelines.path_trace]
type = "Compute"
bindingLayout = "PathTrace"

[pipelines.path_trace.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/path_trace.cs.dxil"

[pipelines.path_trace.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/path_trace.comp.spv"

[pipelines.path_trace_tonemap]
type = "Compute"
bindingLayout = "PathTraceTonemap"

[pipelines.path_trace_tonemap.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/path_trace_tonemap.cs.dxil"

[pipelines.path_trace_tonemap.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/path_trace_tonemap.comp.spv"

[pipelines.equirect_to_cubemap]
type = "Compute"
bindingLayout = "EnvironmentConvert"

[pipelines.equirect_to_cubemap.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/equirect_to_cubemap.cs.dxil"

[pipelines.equirect_to_cubemap.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/equirect_to_cubemap.comp.spv"

[pipelines.ibl_irradiance]
type = "Compute"
bindingLayout = "EnvironmentConvert"

[pipelines.ibl_irradiance.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/ibl_irradiance.cs.dxil"

[pipelines.ibl_irradiance.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/ibl_irradiance.comp.spv"

[pipelines.ibl_prefilter]
type = "Compute"
bindingLayout = "EnvironmentConvert"

[pipelines.ibl_prefilter.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/ibl_prefilter.cs.dxil"

[pipelines.ibl_prefilter.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/ibl_prefilter.comp.spv"

[pipelines.ibl_brdf_lut]
type = "Compute"
bindingLayout = "EnvironmentConvert"

[pipelines.ibl_brdf_lut.shaders.dx12]
compute = "demo/res/compiled_shaders/dx12/ibl_brdf_lut.cs.dxil"

[pipelines.ibl_brdf_lut.shaders.vulkan]
compute = "demo/res/compiled_shaders/vulkan/ibl_brdf_lut.comp.spv"
